
global:
  # domain is the base domain of your cluster, so that the ingress hostname can be constructed as `streamsheets-<namespace><domain>`.
  domain: .my-apps.domain

images:
  repository: ghcr.io/ctron
  # tag allows to specify a specific tag, defaults to the app-version.
  # tag: latest
  # pullPolicy allows to specify a pull policy, defaults to "Always" for "latest" tags, and "IfNotPresent" otherwise.
  pullPolicy: Always

deployExamples: true

defaults:
  logLevel: info

ingress:
  # domain allows to override the global domain.
  # domain: .my-apps.domain
  # host is an alternate way to explicitly configure the hostname of the streamsheets ingress route.
  # host: streamsheets.my-apps.domain
  protocol: https
  annotations:
    kubernetes.io/ingress.class: "nginx"

internalBroker:
  username: internal
  password: internal123456

mongodb:
  image:
    registry: gcr.io
    repository: bitnami-containers/mongodb
  auth:
    rootPassword: admin123456
    database: streamsheets
    username: streamsheets
    password: streamsheets123456
  useStatefulSet: true

redis:
  image:
    registry: gcr.io
    repository: bitnami-containers/redis
  architecture: standalone
  auth:
    enabled: false # streamsheets doesn't support authenticated redis
