{{ $ref := ( dict "root" . "name" "broker" ) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "streamsheets.name" $ref }}
  labels:
  {{- include "streamsheets.labels" $ref | nindent 4 }}
data:
  USERNAME: {{ .Values.internalBroker.username | b64enc | quote }}
  PASSWORD: {{ .Values.internalBroker.password | b64enc | quote }}
