{{ $ref := ( dict "root" . "name" "init" ) }}
{{- if .Values.initialize.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "streamsheets.name" $ref }}
  labels:
    {{- include "streamsheets.labels" $ref | nindent 4 }}
data:
{{- with.Values.initialize.json }}
  init.json: {{ . | quote }}
{{- else -}}
  init.json: |
    {{- tpl ( .Files.Get "config/gateway/init.json" ) . | b64enc | nindent 4 }}
{{- end }}
{{- end }}
