{{ $ref := ( dict "root" . "name" "gateway" ) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamsheets.name" $ref }}
  labels:
    {{- include "streamsheets.labels" $ref | nindent 4 }}
spec:
  type: ClusterIP

  selector:
    {{- include "streamsheets.labels" $ref | nindent 4 }}

  ports:
    - name: gateway
      port: 8080
      targetPort: gateway
