name: Build

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"

jobs:

  check:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          cache: 'yarn'

      - run: yarn install --forzen-lockfile
      - run: yarn workspace @cedalo/gateway build
      - run: yarn workspace @cedalo/webui run local-build
      - run: node scripts/build.js --name ctron/streamsheets --tag ci
