name: Build

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"

jobs:

  check:
    runs-on: ubuntu-20.04

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Login to github container repository
        run: echo "${{ secrets.GHCR_TOKEN }}" | podman login https://ghcr.io -u "${{ github.actor }}" --password-stdin

      - run: make
